Replaced city.h's homespun uint{8,32,64} typedefs with a #include.
This is an attempt to fix build errors that look like this:

    ../../../third_party/cityhash/city.h:52:18: error: conflicting declaration ‘typedef uint64_t uint64’
    ../../../base/integral_types.h:41:28: error: ‘uint64’ has a previous  declaration as ‘typedef long long unsigned int uint64’

I don't understand why exactly this happens; it must be a configuration
difference, since it doesn't happen for me on OS X or Ubuntu.

Fixes issue 7.